[package]
name = "tr01"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = "0.5.0-rc.1"
diesel = { version = "1.4.8", features = ["postgres"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
